beckermr/pizza-cutter-metadetect

bin/run-metadetect-on-slices, config_files/metadetect-v2.yaml, pizza_cutter_metadetect/gaia_stars.py, pizza_cutter_metadetect/run_metadetect.py, pizza_cutter_metadetect/tests/test_gaia_stars.py, pizza_cutter_metadetect/tests/test_run_metadetect.py
=> ENH gaia masking code, buffer regions, other fixes

bin/run-metadetect-on-slices, pizza_cutter_metadetect/run_metadetect.py, pizza_cutter_metadetect/tests/test_get_part_ranges.py, pizza_cutter_metadetect/tests/test_run_metadetect.py, pizza_cutter_metadetect/tests/test_split_range.py
This PR renames columns to start with mdet and keeps the outer buffer of the slices.
=> ENH column rename and keep outer buffer

pizza_cutter_metadetect/tests/test_run_metadetect.py, requirements.txt
This PR adds tests for the mdet code.
=> TST added tests for mdet

pizza_cutter_metadetect/run_metadetect.py
This PR fixes the size of the coadd comp.
=> BUG fix computing the size of the coadd

pizza_cutter_metadetect/gaia_stars.py, pizza_cutter_metadetect/run_metadetect.py, pizza_cutter_metadetect/tests/test_gaia_stars.py
This PR sets mfrac = 1, weight = 0 and bmask to gaia stars if the interp fails
=> ENH set to no obs if gaia interp fails

pizza_cutter_metadetect/gaia_stars.py
This PR shims out an internal api we should not have been using.
=> ENH ref interp api

.github/workflows/tests.yml, config_files/metadetect-v4.yaml, pizza_cutter_metadetect/gaia_stars.py, pizza_cutter_metadetect/masks.py, pizza_cutter_metadetect/run_metadetect.py, pizza_cutter_metadetect/tests/test_gaia_stars.py, pizza_cutter_metadetect/tests/test_masks.py, pizza_cutter_metadetect/tests/test_run_metadetect.py
=> ENH apodizing and using noise interp for GAIA stars

pizza_cutter_metadetect/run_metadetect.py, pizza_cutter_metadetect/tests/test_run_metadetect.py
This PR adds filename/tilename columns, names the table ext, and fixes a bug in getting the tileinfo.
=> BUG add filename and new info struct

bin/run-metadetect-on-slices, pizza_cutter_metadetect/run_metadetect.py
This PR makes the code quieter.
=> ENH make it quieter

pizza_cutter_metadetect/run_metadetect.py
This should fix a processing error we hit.
=> BUG make sure to handle Nones in mdet results

bin/make-coadd-image-from-slices, bin/run-metadetect-on-slices, pizza_cutter_metadetect/run_metadetect.py, pizza_cutter_metadetect/tests/test_run_metadetect.py, setup.py
This PR adds code to visualize the slices.
=> ENH add code to make visualizations of slices

pizza_cutter_metadetect/run_metadetect.py
=> ENH put origin on lower left

bin/run-metadetect-on-slices, pizza_cutter_metadetect/run_metadetect.py, pizza_cutter_metadetect/tests/test_run_metadetect.py
This PR flattens all columns and renames row/col to y/x to make database handling easier. 
closes #30
closes #31
=> REF flatten all columns

pizza_cutter_metadetect/masks.py, pizza_cutter_metadetect/run_metadetect.py, pizza_cutter_metadetect/tests/test_masks.py, requirements.txt
This PR adds flags to the healsparse mask for why things are missing. We may want to pull more detail flags out of mdet but this is a good start.
closes #24
=> ENH track flags for why things are missing

pizza_cutter_metadetect/gaia_stars.py, pizza_cutter_metadetect/masks.py, pizza_cutter_metadetect/run_metadetect.py, pizza_cutter_metadetect/tests/test_gaia_stars.py, requirements.txt
This PR refactors to use some of the tools from the mdet repo.
=> REF use tools from mdet repo

bin/run-metadetect-on-slices, pizza_cutter_metadetect/run_metadetect.py, pizza_cutter_metadetect/tests/test_run_metadetect.py
One input band was not working. I added some error checking too.
=> BUG make sure catalogs work with one band

pizza_cutter_metadetect/run_metadetect.py, pizza_cutter_metadetect/tests/test_run_metadetect.py
This is for testing cuts later.
=> ENH adding nepochs to outputs

pizza_cutter_metadetect/run_metadetect.py
This won't pass until the metadetect update is done.
=> ENH add detected positions stuff

pizza_cutter_metadetect/run_metadetect.py, pizza_cutter_metadetect/tests/test_run_metadetect.py, requirements.txt
=> ENH rename columns

.github/workflows/tests.yml, bin/run-metadetect-on-slices, pizza_cutter_metadetect/run_metadetect.py, pizza_cutter_metadetect/tests/test_run_metadetect.py, requirements.txt
=> ENH multiband mdet

bin/run-metadetect-on-slices
This PR makes a small change to clean out tmp dirs properly.
=> BUG clean out tmpdir properly

bin/run-metadetect-on-slices
This PR moves the commits from 0.6 to main.
=> BUG clean out tmpdir properly (#51)

pizza_cutter_metadetect/run_metadetect.py, pizza_cutter_metadetect/tests/test_run_metadetect.py
=> PERF do not run single bands

bin/run-metadetect-on-slices, pizza_cutter_metadetect/run_metadetect.py, pizza_cutter_metadetect/tests/test_run_metadetect.py, requirements.txt
This PR enables the user to pass which bands for shear from the cli.
=> ENH enable adjusting shear bands from cli

bin/run-metadetect-on-slices, config_files/metadetect-v8.yaml, config_files/metadetect-v9.yaml, pizza_cutter_metadetect/run_metadetect.py, pizza_cutter_metadetect/tests/test_run_metadetect.py, requirements.txt
This PR sets the shear bands and det bands in the config.
=> REF set bands in config
